=== Massas/viky-ai/nlp/tools/makefile/makefile.dtd
<!ELEMENT makefile (type , project_name , revision?, version?, tests?, sources , platforms) >
<!ELEMENT type (#PCDATA)>
<!ELEMENT project_name (#PCDATA)>
<!ELEMENT revision (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT tests (file*) >
<!ELEMENT sources (file*) >
<!ELEMENT file (#PCDATA)>
<!ELEMENT platforms (platform)*>
<!ELEMENT platform (option | sources)*>
<!ATTLIST platform
   name         CDATA         #REQUIRED
>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
   name         CDATA         #REQUIRED
   arch         CDATA         #IMPLIED
>

=== Massas/viky-ai/nlp/sources/ogm_sig/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_sig</project_name>
  <sources>
    <file>isig.c</file>
    <file>signa.c</file>
    <file>signal.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_sig</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogsig</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/sources/ogm_ltras/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_ltras</project_name>
  <sources>
    <file>iltras.c</file>
    <file>ltras.c</file>
    <file>ltrasba.c</file>
    <file>ltrasparse.c</file>
    <file>ltrasfalse.c</file>
    <file>ltrasfalsec.c</file>
    <file>ltrasfc.c</file>
    <file>ltrasfcb.c</file>
    <file>ltrasm.c</file>
    <file>ltrasmadd.c</file>
    <file>ltrasmba.c</file>
    <file>ltrasmconf.c</file>
    <file>ltrasmcost.c</file>
    <file>ltrasmcut.c</file>
    <file>ltrasmcutc.c</file>
    <file>ltrasmdel.c</file>
    <file>ltrasmem.c</file>
    <file>ltrasmexcept.c</file>
    <file>ltrasmexceptc.c</file>
    <file>ltrasmlem1.c</file>
    <file>ltrasmlem2.c</file>
    <file>ltrasmtra.c</file>
    <file>ltrasmmodule.c</file>
    <file>ltrasmlog.c</file>
    <file>ltrasmod.c</file>
    <file>ltrasmpaste.c</file>
    <file>ltrasmphon.c</file>
    <file>ltrasmref.c</file>
    <file>ltrasmswap.c</file>
    <file>ltrasmtest.c</file>
    <file>ltrasmterm.c</file>
    <file>ltrasmtrans.c</file>
    <file>ltrasmword.c</file>
    <file>ltrasmsplit.c</file>
    <file>ltrasmsplitc.c</file>
    <file>ltrasnode.c</file>
    <file>ltrasope.c</file>
    <file>ltrasparam.c</file>
    <file>ltrasres.c</file>
    <file>ltrassug.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">libogltras</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">libogltrap.lib libogheap.lib ogm_stm.lib ogm_pho.lib ogm_ldi.lib ogm_aut.lib ogm_rqp.lib ogm_lip.lib ogm_xml.lib ogm_msg.lib ogm_uni.lib ogm_thr.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogltras</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-lm -logaut -loggen -logheap -logldi -loglip -logltrap -logmsg -logpho -logrqp -logstm -loguni -logxml</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_lip/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_lip</project_name>
  <sources>
    <file>ilip.c</file>
    <file>lip.c</file>
    <file>lipapi.c</file>
    <file>lipalang.c</file>
    <file>lipglang.c</file>
    <file>liplang.c</file>
    <file>lipmem.c</file>
    <file>lipoutputxml.c</file>
    <file>lippawo.c</file>
    <file>lippunct.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_lip</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_auta.lib ogm_aut.lib libogheap.lib ogm_thr.lib ogm_gen.lib ogm_msg.lib ogm_xml.lib ogm_uni.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">oglip</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -logauta -logheap -loggen -logmsg -loguni -logxml</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_aut/prog/ogfemin/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogfemin</project_name>
  <sources>
    <file>ogfemin.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogfemin.exe</option>
      <option name="ADD_LIBR">ogm_aut.lib ogm_gen.lib ogm_thr.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogfemin</option>
      <option name="ADD_CFLAGS"></option>
      <option name="ADD_LIBS">-logaut -logthr -loggen</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_nls/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_nls</project_name>
  <sources>
    <file>inls.c</file>
    <file>nlsconf.c</file>
    <file>nlsimport.c</file>
    <file>nlsonem.c</file>
    <file>nlsrun.c</file>
    <file>nlslog.c</file>
    <file>nlslt.c</file>
    <file>nlserror.c</file>
    <file>nlsltp.c</file>
    <file>nlsltu.c</file>
    <file>nls_endpoints.c</file>
    <file>nls_endpoint_test.c</file>
    <file>nls_endpoint_dump.c</file>
    <file>nls_endpoint_interpret.c</file>
    <file>nls_endpoint_packages.c</file>
    <file>nlsmt.c</file>
  </sources>
  <platforms>
    <platform name="linux">
      <option name="NAME">ognls</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-lognlp -logaddr -loguci -logsock -logthr -logheap -logmsg -loggen -lglib-2.0 -ljansson -luriparser</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_auta/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_auta</project_name>
  <sources>
    <file>charset.c</file>
    <file>delword.c</file>
    <file>entity.c</file>
    <file>quaranti.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_auta</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_aut.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogauta</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_ltrac/prog/ogltrac/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogltrac</project_name>
  <sources>
    <file>ogltrac.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogltrac.exe</option>
      <option name="ADD_LIBR">libogltrac.lib ogm_auta.lib ogm_thr.lib ogm_gen.lib ogm_uni.lib ogm_msg.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogltrac</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logauta -loggen -logltrac -logmsg -logthr</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_ltrap/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_ltrap</project_name>
  <sources>
    <file>iltrap.c</file>
    <file>ltrap.c</file>
    <file>ltrapba.c</file>
    <file>ltraplog.c</file>
    <file>ltrapseq.c</file>
    <file>ltrapsmall.c</file>
    <file>ltrapsol.c</file>
    <file>ltrapspan.c</file>
    <file>ltrapspansol.c</file>
    <file>ltrapsolution.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">libogltrap</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_aut.lib ogm_uni.lib ogm_msg.lib ogm_thr.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogltrap</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -loggen -logmsg -loguni</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>
