=== Massas/viky-ai/nlp/tools/makefile/makefile.dtd
<!ELEMENT makefile (type , project_name , revision?, version?, tests?, sources , platforms) >
<!ELEMENT type (#PCDATA)>
<!ELEMENT project_name (#PCDATA)>
<!ELEMENT revision (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT tests (file*) >
<!ELEMENT sources (file*) >
<!ELEMENT file (#PCDATA)>
<!ELEMENT platforms (platform)*>
<!ELEMENT platform (option | sources)*>
<!ATTLIST platform
   name         CDATA         #REQUIRED
>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
   name         CDATA         #REQUIRED
   arch         CDATA         #IMPLIED
>

=== Massas/viky-ai/nlp/sources/ogm_ltras/prog/ogltras/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogltras</project_name>
  <sources>
    <file>ogltras.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogltras.exe</option>
      <option name="ADD_LIBR">libogltras.lib ogm_auta.lib ogm_thr.lib ogm_gen.lib ogm_uni.lib ogm_msg.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogltras</option>
      <option name="ADD_CFLAGS"></option>
      <option name="ADD_LIBS">-lglib-2.0 -logheap -logltras -logldi -logeql -logltrap -logpho -logstm -loglip -logrqp -logthr -liconv -loguni -loggen -logaut -logauta -logxml -logmsg -logauta</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_sock/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_sock</project_name>
  <sources>
    <file>ghbyaddr.c</file>
    <file>ogm_sock.c</file>
    <file>sockconn.c</file>
    <file>sockmisc.c</file>
    <file>urlhead.c</file>
    <file>urlhlog.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_sock</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogsock</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_stm/lib/makefile.xml
<?xml version="1.0"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_stm</project_name>
  <revision>$Revision: 1171 $</revision>
  <sources>
    <file>istm.c</file>
    <file>stmlev.c</file>
    <file>stmlevcompute.c</file>
    <file>stmlevutils.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_stm</option>
      <option name="ADD_LIBR">ogm_gen.lib ogm_thr.lib ogm_msg.lib ogm_uni.lib ogm_auta.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogstm</option>
      <option name="ADD_CFLAGS">-I$(OG_REPO_PATH)/sources/include/glib-2.0</option>
      <option name="ADD_LIBR">-lglib-2.0 -logheap -loggen -logmsg -loguni -loglip</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_aut/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_aut</project_name>
  <sources>
    <file>auf.c</file>
    <file>auf2t.c</file>
    <file>aufgline.c</file>
    <file>auflet.c</file>
    <file>aufsave.c</file>
    <file>aufscan.c</file>
    <file>auftry.c</file>
    <file>aug.c</file>
    <file>augscan.c</file>
    <file>aum.c</file>
    <file>aumbuild.c</file>
    <file>aut.c</file>
    <file>autadd.c</file>
    <file>autaline.c</file>
    <file>autcopy.c</file>
    <file>autdel.c</file>
    <file>autdele.c</file>
    <file>autfinal.c</file>
    <file>autflush.c</file>
    <file>autfreq.c</file>
    <file>autget.c</file>
    <file>autgline.c</file>
    <file>autinit.c</file>
    <file>autlet.c</file>
    <file>autlstmin.c</file>
    <file>autmem.c</file>
    <file>autmisc.c</file>
    <file>autput.c</file>
    <file>autreset.c</file>
    <file>autsave.c</file>
    <file>autscan.c</file>
    <file>autstat.c</file>
    <file>autstate.c</file>
    <file>auttry.c</file>
    <file>autu.c</file>
    <file>ogauf.c</file>
    <file>ogaufscan.c</file>
    <file>autendian.c</file>
    <file>autefstate.c</file>
    <file>autestate.c</file>
    <file>autegstate.c</file>
    <file>autefrstate.c</file>
    <file>aul.c</file>
    <file>auldecl.c</file>
    <file>aulscan.c</file>
    <file>autpri.c</file>
    <file>aufbuf.c</file>
    <file>autadde.c</file>
    <file>autscane.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_aut</option>
      <option name="ADD_INC"></option>
      <option name="ADD_LIBR">ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogaut</option>
      <option name="ADD_CFLAGS"></option>
      <option name="ADD_LIBR">-loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_rqp/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_rqp</project_name>
  <sources>
    <file>irqp.c</file>
    <file>rqpapi.c</file>
    <file>rqpba.c</file>
    <file>rqpbx.c</file>
    <file>rqpclean.c</file>
    <file>rqpequiv.c</file>
    <file>rqpfpar.c</file>
    <file>rqpfunc.c</file>
    <file>rqplog.c</file>
    <file>rqpmem.c</file>
    <file>rqpminus.c</file>
    <file>rqpmisc.c</file>
    <file>rqpnode.c</file>
    <file>rqpnormd.c</file>
    <file>rqpparse.c</file>
    <file>rqpprety.c</file>
    <file>rqppretyxml.c</file>
    <file>rqpprior.c</file>
    <file>rqprepar.c</file>
    <file>rqpstruc.c</file>
    <file>rqpsubtree.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_rqp</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_aut.lib ogm_uni.lib ogm_msg.lib ogm_xml.lib ogm_thr.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogrqp</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -loggen -logmsg -logthr -loguni -logxml</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/sources/ogm_http/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_http</project_name>
  <sources>
    <file>httpba.c</file>
    <file>httpmem.c</file>
    <file>httphrl.c</file>
    <file>httphrli.c</file>
    <file>httphrlo.c</file>
    <file>httphrr.c</file>
    <file>httphrscan.c</file>
    <file>httphrty.c</file>
    <file>ihttp.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_http</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_aut.lib ogm_msg.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">oghttp</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -logmsg -loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/sources/ogm_uci/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_uci</project_name>
  <sources>
    <file>iuci.c</file>
    <file>iucic.c</file>
    <file>iucis.c</file>
    <file>uciba.c</file>
    <file>ucicba.c</file>
    <file>ucimem.c</file>
    <file>ucircreq.c</file>
    <file>uciread.c</file>
    <file>ucisba.c</file>
    <file>ucismem.c</file>
    <file>ucisread.c</file>
    <file>uciswrite.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_uci</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_http.lib ogm_sock.lib ogm_msg.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">oguci</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-loggen -loghttp -logsock -logmsg</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_thr/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_thr</project_name>
  <sources>
    <file>ogm_thr.c</file>
    <file>thrlog.c</file>
    <file>thrmutex.c</file>
    <file>thrsem.c</file>
    <file>thrterm.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_thr</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogthr</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>
