=== Massas/viky-ai/nlp/tools/makefile/makefile.dtd
<!ELEMENT makefile (type , project_name , revision?, version?, tests?, sources , platforms) >
<!ELEMENT type (#PCDATA)>
<!ELEMENT project_name (#PCDATA)>
<!ELEMENT revision (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT tests (file*) >
<!ELEMENT sources (file*) >
<!ELEMENT file (#PCDATA)>
<!ELEMENT platforms (platform)*>
<!ELEMENT platform (option | sources)*>
<!ATTLIST platform
   name         CDATA         #REQUIRED
>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
   name         CDATA         #REQUIRED
   arch         CDATA         #IMPLIED
>

=== Massas/viky-ai/sources/ogm_sysi/prog/ogsysi/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogsysi</project_name>
  <sources>
    <file>ogsysi.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogsysi.exe</option>
      <option name="ADD_LIBR">libogpsync.lib libogsysi.lib ogm_msg.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogsysi</option>
      <option name="LINKER_NO_UNDEF">yes</option>
      <option name="ADD_CFLAGS"></option>
      <option name="ADD_LIBS">-logsysi -lglib-2.0 -loggen -lxml2 -logmisc -logthr -logmsg -logsam -logpsync</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_ghbn/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_ghbn</project_name>
  <sources>
    <file>ghbn.c</file>
    <file>ghbn_to.c</file>
    <file>ighbn.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_ghbn</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_aut.lib ogm_xpt.lib ogm_thr.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogghbn</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -loggen -logxpt</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nlp/sources/ogm_uni/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_uni</project_name>
  <sources>
    <file>cjkpunct.c</file>
    <file>convunic.c</file>
    <file>cp1250.c</file>
    <file>cp1251.c</file>
    <file>cp1252.c</file>
    <file>cp1256.c</file>
    <file>cp850.c</file>
    <file>cp866.c</file>
    <file>cp8859_2.c</file>
    <file>cp8859_5.c</file>
    <file>cpbig5.c</file>
    <file>cp936.c</file>
    <file>cpgb2312.c</file>
    <file>cpname.c</file>
    <file>cpon.c</file>
    <file>cptocp.c</file>
    <file>cptouni.c</file>
    <file>getcp.c</file>
    <file>isuni.c</file>
    <file>isutf8.c</file>
    <file>ogja.c</file>
    <file>unipos.c</file>
    <file>unitocp.c</file>
    <file>utf8.c</file>
    <file>utf8per.c</file>
    <file>utocp.c</file>
  </sources>
  <platforms>
    <platform name="linux">
      <option name="NAME">oguni</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logauta -loggen -lglib-2.0</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_aut/prog/ogaut/makefile_static.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogaut</project_name>
  <sources>
    <file>ogaut.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogaut.exe</option>
      <option name="ADD_LIBR">ogm_thr_a.lib ogm_gen_a.lib ogm_aut_a.lib ogm_uni_a.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogaut</option>
      <option name="ADD_CFLAGS"></option>
      <option name="ADD_LIBR">$(RLINKPATH)/libogaut.a  $(RLINKPATH)/liboguni.a $(RLINKPATH)/libogauta.a $(RLINKPATH)/liboggen.a $(RLINKPATH)/libogthr.a</option>
      <option name="ADD_LIBD">$(DLINKPATH)/libogaut.a  $(DLINKPATH)/liboguni.a $(DLINKPATH)/libogauta.a $(DLINKPATH)/liboggen.a $(DLINKPATH)/libogthr.a</option>
      <option name="ADD_LIBP">$(PLINKPATH)/libogaut.a  $(PLINKPATH)/liboguni.a $(PLINKPATH)/libogauta.a $(PLINKPATH)/liboggen.a $(PLINKPATH)/libogthr.a</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_uci/prog/ogucic/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>prog</type>
  <project_name>ogucic</project_name>
  <sources>
    <file>ogucic.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogucic.exe</option>
      <option name="ADD_LIBR">ogm_uci.lib ogm_sock.lib ogm_msg.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogucic</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-loggen -logsock -logmsg -loguci</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/sources/ogm_nls/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_nls</project_name>
  <sources>
    <file>inls.c</file>
    <file>nlsconf.c</file>
    <file>nlsonem.c</file>
    <file>nlsrun.c</file>
    <file>nlslog.c</file>
    <file>nlslt.c</file>
    <file>nlslter.c</file>
    <file>nlsltp.c</file>
    <file>nlsltu.c</file>
  </sources>
  <platforms>
    <platform name="linux">
      <option name="NAME">ognls</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaddr -logxml -loguci -logsock -logthr -logheap -logmsg -loggen</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/nls/sources/ogm_sysi/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_sysi</project_name>
  <sources>
    <file>isysi.c</file>
    <file>sysiwrite.c</file>
    <file>sysiread.c</file>
    <file>sysilog.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">libogsysi</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_msg.lib ogm_gen.lib libogmisc.lib libogsam.lib libogpsync.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogsysi</option>
      <option name="ADD_CFLAGS"/>
      <option name="LINKER_NO_UNDEF">yes</option>
      <option name="ADD_LIBR">-logmsg -loggen -logthr -lglib-2.0 -lgthread-2.0</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>

=== Massas/viky-ai/sources/ogm_pho/lib/makefile.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE makefile SYSTEM "makefile.dtd">
<makefile>
  <type>lib</type>
  <project_name>ogm_pho</project_name>
  <sources>
    <file>ipho.c</file>
    <file>pho.c</file>
    <file>phoanaly.c</file>
    <file>phoaut.c</file>
    <file>phoba.c</file>
    <file>phoclass.c</file>
    <file>phoexp.c</file>
    <file>phoforma.c</file>
    <file>phomatch.c</file>
    <file>phomem.c</file>
    <file>phoreadc.c</file>
    <file>phorule.c</file>
    <file>phorules.c</file>
    <file>phowrite.c</file>
  </sources>
  <platforms>
    <platform name="win">
      <option name="NAME">ogm_pho</option>
      <option name="ADD_INC"/>
      <option name="ADD_LIBR">ogm_thr.lib ogm_xml.lib ogm_uni.lib ogm_aut.lib ogm_msg.lib ogm_gen.lib</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
    <platform name="linux">
      <option name="NAME">ogpho</option>
      <option name="ADD_CFLAGS"/>
      <option name="ADD_LIBR">-logaut -loggen -logmsg -loguni -logxml</option>
      <option name="ADD_LIBD">$(ADD_LIBR)</option>
      <option name="ADD_LIBP">$(ADD_LIBR)</option>
    </platform>
  </platforms>
</makefile>
