=== Massas/viky-ai/nls/products/pmanifest.dtd
<!ELEMENT product_manifest (info, use, instances?, packaging*)>
<!ATTLIST product_manifest
   commercial_name CDATA     #REQUIRED
   parent          CDATA     #IMPLIED
>
<!ELEMENT info (version?, summary, license, vendor, url, description)>
<!ELEMENT version EMPTY>
<!ATTLIST version
   major        CDATA        #REQUIRED
   minor        CDATA        #REQUIRED
   fix          CDATA        #REQUIRED
   revision     CDATA        #IMPLIED
>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT vendor  (#PCDATA)>
<!ELEMENT url     (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT use (resource | component)* >
<!ELEMENT resource EMPTY>
<!ATTLIST resource
   name         CDATA         #REQUIRED
>
<!ELEMENT component EMPTY>
<!ATTLIST component
   name         CDATA         #REQUIRED
>
<!ELEMENT packaging (instance | ship | package)* >
<!ATTLIST packaging
   platform     (linux|win|all)   #IMPLIED
>
<!ELEMENT ship (module | directory | file | lib | bin | copy | link | rename | lhp)*>

<!ELEMENT module EMPTY>
<!ATTLIST module
   source       CDATA             #REQUIRED
>

<!ELEMENT directory (module | directory | file | lib | bin | copy | link | rename | lhp)*>
<!ATTLIST directory
   name         CDATA             #REQUIRED
   permissions  CDATA             #IMPLIED
   owner        CDATA             #IMPLIED
   group        CDATA             #IMPLIED
   info         CDATA             #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>
<!ELEMENT file EMPTY>
<!ATTLIST file
   name         CDATA             #REQUIRED
   source       CDATA             #REQUIRED
   strip        CDATA             #IMPLIED
   permissions  CDATA             #IMPLIED
   owner        CDATA             #IMPLIED
   group        CDATA             #IMPLIED
   info         CDATA             #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT lib EMPTY>
<!ATTLIST lib
   name         CDATA             #REQUIRED
   source       CDATA             #REQUIRED
   strip        CDATA             #IMPLIED
   permissions  CDATA             #IMPLIED
   owner        CDATA             #IMPLIED
   group        CDATA             #IMPLIED
   info         CDATA             #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT bin EMPTY>
<!ATTLIST bin
   name         CDATA             #REQUIRED
   source       CDATA             #REQUIRED
   strip        CDATA             #IMPLIED
   permissions  CDATA             #IMPLIED
   owner        CDATA             #IMPLIED
   group        CDATA             #IMPLIED
   info         CDATA             #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT link EMPTY>
<!ATTLIST link
   name         CDATA         #REQUIRED
   target       CDATA         #REQUIRED
   permissions  CDATA         #IMPLIED
   owner        CDATA         #IMPLIED
   group        CDATA         #IMPLIED
   info         CDATA         #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT lhp (#PCDATA)>
<!ATTLIST lhp
   name         CDATA            #REQUIRED
   source       CDATA            #REQUIRED
   permissions  CDATA            #IMPLIED
   owner        CDATA            #IMPLIED
   group        CDATA            #IMPLIED
   info         CDATA            #IMPLIED
   platform     (linux|win|all)  #IMPLIED
>

<!ELEMENT rename EMPTY>
<!ATTLIST rename
   name         CDATA             #REQUIRED
   target       CDATA             #REQUIRED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT copy EMPTY>
<!ATTLIST copy
   source       CDATA             #REQUIRED
   target       CDATA             #IMPLIED
   platform     (linux|win|all)   #IMPLIED
>

<!ELEMENT instances (instance+)>

<!ELEMENT instance (directory | file | lib | bin | copy | link | rename | lhp)* >
<!ATTLIST instance
   name         CDATA         #REQUIRED
>

<!ELEMENT package (var*)>
<!ATTLIST package
   platform         (linux|win)       #REQUIRED
   default_location CDATA             #REQUIRED
>

<!ELEMENT var (#PCDATA)>
<!ATTLIST var
   name             CDATA             #REQUIRED
>

=== Massas/viky-ai/nlp/products/bu2_nls/manifest.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE product_manifest SYSTEM "pmanifest.dtd" >
<product_manifest commercial_name="nls">

  <info>
    <version major="0" minor="1" fix="0" />
    <summary>Pertimm NLS</summary>
    <license>(C) Copyright Pertimm</license>
    <vendor>Pertimm</vendor>
    <url>http://www.pertimm.com</url>
    <description>Pertimm Natural Language Server</description>
  </info>

  <use>

    <component name="external_dependencies" />

    <!-- Pertimm libs -->
    <component name="ogm_gen/lib" />
    <component name="ogm_aut/lib" />
    <component name="ogm_xpt/lib" />
    <component name="ogm_thr/lib" />
    <component name="ogm_sig/lib" />
    <component name="ogm_auta/lib" />
    <component name="ogm_uni/lib" />
    <component name="ogm_msg/lib" />
    <component name="ogm_sysi/lib" />
    <component name="ogm_heap/lib" />
    <component name="ogm_sock/lib" />
    <component name="ogm_zlib/lib" />
    <component name="ogm_ghbn/lib" />
    <component name="ogm_addr/lib" />
    <component name="ogm_http/lib" />
    <component name="ogm_uci/lib" />
    <component name="ogm_xml/lib" />
    <component name="ogm_ltrap/lib" />
    <component name="ogm_lip/lib" />
    <component name="ogm_stm/lib" />
    <component name="ogm_pho/lib" />
    <component name="ogm_rqp/lib" />
    <component name="ogm_ltrac/lib" />
    <component name="ogm_ltras/lib" />
    <component name="ogm_nlp/lib" />
    <component name="ogm_nls/lib" />

    <!-- programs -->
    <component name="ogm_nlp/prog/ognlp" />
    <component name="ogm_nls/prog/ogm_nls" />

  </use>

  <packaging>
    <ship>
      <directory name="%COMMERCIAL_NAME%-%SVNREV%">

        <file name="LICENSE.TXT" source="%OG_REPO_PATH%/products/bu2_nls/LICENSE.TXT" />

        <bin name="ogm_nls" source="%OG_REPO_PATH%/build/%TARGET%/bin/ogm_nls" />
        <bin name="ognlp" source="%OG_REPO_PATH%/build/%TARGET%/bin/ognlp" />

        <copy source="%OG_REPO_PATH%/products/bu2_nls/conf" target="./" platform="linux" />
        <copy source="%OG_REPO_PATH%/products/bu2_nls/ling" target="./" platform="linux" />

        <directory name="control" />
        <directory name="log" />
        <directory name="import" />

        <!-- Linux specific -->
        <directory name="lib" platform="linux">
          <directory name="linux" platform="linux">

            <copy source="%OG_REPO_PATH%/build/%TARGET%/bin/*.so*" target="./" platform="linux" />

          </directory>
        </directory>

      </directory>
    </ship>
  </packaging>
</product_manifest>
